export const PATH_HOME = '/';
export const PATH_LOGIN = '/users/login';
export const PATH_SIGNUP = '/users/signup';
export const PATH_USER_EDIT = '/users/edit';
export const PATH_SIGNUP_COMPLETE = '/users/signup/complete';
export const PATH_MYPAGE = '/users/mypage';
export const PATH_POINT_HISTORY = '/users/point-history';
export const PATH_STUDY_CREATE = '/studies/create';
export const PATH_STUDY_DETAIL = '/studies'; // :id
export const PATH_JOINED_STUDY_LIST = '/users/studies';
export const PATH_JOINED_STUDY_DETAIL = '/users/studies'; // :id
export const PATH_STUDY_PARTICIPATION = `/studies/:id/participation`;
export const PATH_PAYMENT = '/payment';
export const PATH_PAYMENT_SUCCESS = '/payment/success';
export const PATH_PAYMENT_FAIL = '/payment/fail';
export const PATH_REFUND = '/refund';
export const PATH_STUDY_RESERVATION_LIST = '/users/studies/:id/reservation';
export const PATH_STUDY_RESERVATION_CREATION = '/reservation/creation';
export const PATH_NOT_FOUND = '/*';
